# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20160316_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='send_mail',
        ),
    ]
