# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0007_auto_20160316_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhit',
            name='notified_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
