# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ahjo', '0010_auto_20160420_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('selector', models.CharField(help_text='Kommentti liittyy t\xe4h\xe4n elementtiin', max_length=200)),
                ('quote', models.TextField(help_text='Sitaatti vaaditaan', verbose_name='Sitaatti')),
                ('text', models.TextField(verbose_name='Kommentti')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment2_set', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment2_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('text',),
                'verbose_name': 'kommentti',
                'verbose_name_plural': 'kommentteja',
            },
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "cars_tires" table to "tires_tires" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
