# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 09:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ahjo', '0002_auto_20160302_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(help_text='This is the element where the comment attaches on a decision', max_length=200)),
                ('quote', models.TextField(help_text='Quotes are required.', verbose_name='Quote')),
                ('text', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('text',),
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'get_latest_by': 'last_modified_time', 'ordering': ('-last_modified_time',), 'verbose_name': 'agenda item', 'verbose_name_plural': 'agenda items'},
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='original',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='comment',
            name='agendaitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahjo.AgendaItem'),
        ),
    ]
