# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0005_subscription_previous_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('send_mail', models.BooleanField(default=False, verbose_name='Sends email')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'subscribed user',
                'verbose_name_plural': 'subscribed users',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriptionuser',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_users',
            field=models.ManyToManyField(through='subscriptions.SubscriptionUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
