# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 15:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionhit_notified_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionhit',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'subscription hit', 'verbose_name_plural': 'subscription hits'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
