# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 12:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahjo_id', models.IntegerField(db_index=True)),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('preparer', models.CharField(max_length=100, null=True, verbose_name='Preparer')),
                ('resolution', models.CharField(choices=[('PASSED_UNCHANGED', 'Passed as drafted'), ('PASSED_VOTED', 'Passed after a vote'), ('PASSED_REVISED', 'Passed revised by presenter'), ('PASSED_MODIFIED', 'Passed modified'), ('REJECTED', 'Rejected'), ('NOTED', 'Noted as informational'), ('RETURNED', 'Returned to preparation'), ('REMOVED', 'Removed from agenda'), ('TABLED', 'Tabled'), ('ELECTION', 'Election')], max_length=20, verbose_name='Resolution')),
                ('classification_code', models.CharField(max_length=20, null=True, verbose_name='Classification code')),
                ('last_modified_time', models.DateTimeField(null=True, verbose_name='Last modified time')),
                ('original', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'get_latest_by': 'last_modified_time',
                'verbose_name': 'agenda item',
                'verbose_name_plural': 'agenda items',
            },
        ),
    ]
