# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahjo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='ahjo_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='resolution',
            field=models.CharField(choices=[('PASSED_UNCHANGED', 'Passed as drafted'), ('PASSED_VOTED', 'Passed after a vote'), ('PASSED_REVISED', 'Passed revised by presenter'), ('PASSED_MODIFIED', 'Passed modified'), ('REJECTED', 'Rejected'), ('NOTED', 'Noted as informational'), ('RETURNED', 'Returned to preparation'), ('REMOVED', 'Removed from agenda'), ('TABLED', 'Tabled'), ('ELECTION', 'Election'), ('UNKNOWN', 'Unknown')], max_length=20, verbose_name='Resolution'),
        ),
    ]
