# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ahjo', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
