# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahjo', '0005_agendaitem_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='has_revisions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='ahjo_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
