# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahjo', '0008_auto_20160420_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='agendaitem',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
