# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-10 11:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_date', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'content_date',
            },
        ),
        migrations.CreateModel(
            name='PolygonIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_date', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'content_date',
            },
        ),
    ]
