# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointindex',
            options={'get_latest_by': 'content_date', 'ordering': ('-content_date',)},
        ),
        migrations.AlterModelOptions(
            name='polygonindex',
            options={'get_latest_by': 'content_date', 'ordering': ('-content_date',)},
        ),
    ]
